project:
  type: book

book:
  title: "book"
  author: "Norah Jones"
  date: "9/19/2024"
  chapters:
    - index.qmd
    - linear_algebra.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



